title: #Test
logo: /assets/img/logo.png
description: This is a <strong>Sample Website</strong>. We used a Jekyll theme for GitHub Pages here.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
